language: cpp

env:
  global:
    # Ubuntu version
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # Global build options and C++ flags
    #- CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
    # Misc
    # - RUN_TESTS=true
    # - COVERAGE=false

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc
      addons:
       apt:
         packages: &precise_latest_boost_packages
           - gcc-4.8
           - g++-4.8
           #- gcov-4.9
           - clang-3.7
           # - valgrind
           # Misc
           # - python-yaml
           # - lcov
           # - libopencv-dev
         sources: &precise_latest_boost_sources
           - ubuntu-toolchain-r-test
           # - llvm-toolchain-precise-3.7
    
before_install:
    # Combine global build options with OS/compiler-dependent options
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

install:
    - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v
    # - sudo pip install codecov
    
    # Download and install recent cmake
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        CMAKE_URL="https://cmake.org/files/v3.11/cmake-3.11.4.tar.gz"
        mkdir -p ${DEPS_DIR}/cmake
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      fi

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DENABLE_TESTING=ON -DENABLE_GTEST=ON  .. 
     - make
     - make test

after_success:
    # Creating report
  # - cd ${TRAVIS_BUILD_DIR}
  # - lcov --directory . --capture --output-file coverage.info # capture coverage info
  # - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  # - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  # - bash <(curl -s https://codecov.io/bash) -t ${CODECOV-UUID-REPO-TOKEN} || echo "Codecov did not collect coverage reports"

notifications:
  email:
    - huxinbang@gmail.com

