#ifndef IOT_CONST_01091047_H
#define IOT_CONST_01091047_H

typedef enum _tc_iot_sys_code_e {
    TC_IOT_SUCCESS = 0,
    TC_IOT_FAILURE = -90,
    TC_IOT_INVALID_PARAMETER = -91,
    TC_IOT_NULL_POINTER = -92,
    TC_IOT_TLS_NOT_SUPPORTED = -93,
    TC_IOT_BUFFER_OVERFLOW = -94,

    TC_IOT_NETWORK_ERROR_BASE = -100,
    TC_IOT_NET_CONNECT_FAILED = -101,
    TC_IOT_NET_UNKNOWN_HOST = -102,
    TC_IOT_NET_SOCKET_FAILED = -103,
    TC_IOT_SEND_PACK_FAILED = -104,

    TC_IOT_MQTT_RECONNECT_TIMEOUT = -150,
    TC_IOT_MQTT_RECONNECT_IN_PROGRESS = -151,
    TC_IOT_MQTT_RECONNECT_FAILED = -152,
    TC_IOT_MQTT_NETWORK_UNAVAILABLE = -153,
    TC_IOT_MQTT_WAIT_ACT_TIMEOUT = -154,

    TC_IOT_MBED_TLS_ERROR_BASE = -200,
    TC_IOT_CTR_DRBG_SEED_FAILED = -201,
    TC_IOT_X509_CRT_PARSE_FILE_FAILED = -202,
    TC_IOT_PK_PRIVATE_KEY_PARSE_ERROR = -203,
    TC_IOT_PK_PARSE_KEYFILE_FAILED = -204,
    TC_IOT_TLS_NET_SET_BLOCK_FAILED = -205,
    TC_IOT_TLS_SSL_CONFIG_DEFAULTS_FAILED = -206,
    TC_IOT_TLS_SSL_CONF_OWN_CERT_FAILED = -207,
    TC_IOT_TLS_SSL_SETUP_FAILED = -208,
    TC_IOT_TLS_SSL_SET_HOSTNAME_FAILED = -209,
    TC_IOT_TLS_SSL_HANDSHAKE_FAILED = -210,
    TC_IOT_TLS_X509_CRT_VERIFY_FAILED = -211,
    TC_IOT_TLS_SSL_WRITE_FAILED = -212,
    TC_IOT_TLS_SSL_WRITE_TIMEOUT = -213,
    TC_IOT_TLS_SSL_READ_FAILED = -214,
    TC_IOT_TLS_SSL_READ_TIMEOUT = -215,
    TC_IOT_TLS_MD_SETUP_FAILED = -216,

    TC_IOT_LOGIC_ERROR_BASE = -1000,
    TC_IOT_NETWORK_PTR_NULL = -1001,
    TC_IOT_NETCONTEXT_PTR_NULL = -1002,
    TC_IOT_JSON_PATH_NO_MATCH = -1003,
    TC_IOT_JSON_PARSE_FAILED = -1004,
    TC_IOT_ERROR_HTTP_REQUEST_FAILED = -1005,
    TC_IOT_REFRESH_TOKEN_FAILED = -1006,

} tc_iot_sys_code_e;

#endif /* end of include guard */
