#ifndef TC_IOT_COMPILE_FLAGS_H
#define TC_IOT_COMPILE_FLAGS_H

#define ENABLE_MQTT
#define ENABLE_OTA
#define ENABLE_DATA_TEMPLATE

#define ENABLE_COAP

#define ENABLE_TLS
/* #undef ENABLE_DTLS */

#define ENABLE_STACK_TRACE_LOG
#define ENABLE_MQTT_RECONNECT_FOREVER

// Enabled Log Levels
#define ENABLE_TC_IOT_LOG_TRACE
#define ENABLE_TC_IOT_LOG_DEBUG
#define ENABLE_TC_IOT_LOG_INFO
#define ENABLE_TC_IOT_LOG_WARN
#define ENABLE_TC_IOT_LOG_ERROR
#define ENABLE_TC_IOT_LOG_FATAL

#endif /* end of include guard */
