#!/bin/bash

PRODUCT_ID=${TENCENT_CLOUD_DEMO_PRODUCT_ID}
DEVICE_NAME=${TENCENT_CLOUD_DEMO_DEVICE_NAME}
DEVICE_SECRET=${TENCENT_CLOUD_DEMO_DEVICE_SECRET}
MQTT_PASSWORD=${TENCENT_CLOUD_DEMO_PASSWORD}
MQTT_HOST=${TENCENT_CLOUD_DEMO_MQTT_HOST}
MQTT_CLIENT_ID=${TENCENT_CLOUD_DEMO_MQTT_CID}
 
MQTT_CMD="../build/bin/demo_mqtt --trace -t ${PRODUCT_ID} -d ${DEVICE_NAME} -P ${MQTT_PASSWORD}  -h ${MQTT_HOST} "

if [ -n DEVICE_SECRET ];then
	MQTT_CMD="$MQTT_CMD -s ${DEVICE_SECRET}"
fi

if [ -n $MQTT_CLIENT_ID ];then
	MQTT_CMD="$MQTT_CMD -i ${MQTT_CLIENT_ID}"
fi

echo ${MQTT_CMD}
${MQTT_CMD}

