#!/bin/bash

PRODUCT_ID=${TENCENT_CLOUD_DEMO_PRODUCT_ID}
DEVICE_NAME=${TENCENT_CLOUD_DEMO_DEVICE_NAME}
DEVICE_SECRET=${TENCENT_CLOUD_DEMO_DEVICE_SECRET}
MQTT_PASSWORD=${TENCENT_CLOUD_DEMO_PASSWORD}
MQTT_HOST=${TENCENT_CLOUD_DEMO_MQTT_HOST}
MQTT_CLIENT_ID=${TENCENT_CLOUD_DEMO_MQTT_CID}

echo ${#MQTT_CLIENT_ID}
 
MQTT_CMD="../build/bin/basic_mqtt --trace -t ${PRODUCT_ID} -d ${DEVICE_NAME} -h ${MQTT_HOST} "

if [ ${#DEVICE_SECRET} -gt 0 ];then
	MQTT_CMD="$MQTT_CMD -s ${DEVICE_SECRET}"
fi

if [ ${#MQTT_CLIENT_ID} -gt 0 ];then
	MQTT_CMD="$MQTT_CMD -i ${MQTT_CLIENT_ID}"
fi

if [ ${#MQTT_PASSWORD} -gt 0 ];then
        MQTT_CMD="$MQTT_CMD -P ${MQTT_PASSWORD}"
fi

echo ${MQTT_CMD}
${MQTT_CMD}

