#!/bin/bash

PRODUCT_ID=${TENCENT_CLOUD_DEMO_PRODUCT_ID}
DEVICE_NAME=${TENCENT_CLOUD_DEMO_DEVICE_NAME}
DEVICE_SECRET=${TENCENT_CLOUD_DEMO_DEVICE_SECRET}
MQTT_PASSWORD=${TENCENT_CLOUD_DEMO_PASSWORD}
MQTT_HOST=${TENCENT_CLOUD_DEMO_MQTT_HOST}
MQTT_CMD="../build/bin/demo_mqtt -t ${PRODUCT_ID} -d ${DEVICE_NAME} -P ${MQTT_PASSWORD} -s ${DEVICE_SECRET} -h ${MQTT_HOST}  --verbose"

echo ${MQTT_CMD}
${MQTT_CMD}
#./demo_mqtt -t ${PRODUCT_ID} -d ${DEVICE_NAME} -P ${MQTT_PASSWORD} -s ${DEVICE_SECRET} -h ${MQTT_HOST}  --verbose
